/*ELIMINAR CONFIGURACION DE TABLAs*/
IF(OBJECT_ID('IAContacto') > 0)
	DROP TABLE IAContacto
IF(OBJECT_ID('IAUsuario') > 0)
	DROP TABLE IAUsuario

/*CREACION DE TABLAs*/
CREATE TABLE IAUsuario(
	IdUsuario INT IDENTITY (1,1),
	Nickname VARCHAR(50) NOT NULL,
	FechaRegistro DATE CONSTRAINT DF_IAUsuario_FechaRegistro DEFAULT GETDATE(),
	Correo VARCHAR(100) NOT NULL UNIQUE,
	Contrasena VARCHAR(MAX) NOT NULL,
	Estatus BIT CONSTRAINT DF_IAUsuario_Estatus DEFAULT 1,
	PRIMARY KEY(IdUsuario)
);
CREATE TABLE IAContacto(
	IdConctacto INT IDENTITY (1,1),
	FechaRegistro DATE CONSTRAINT DF_IAContacto_FechaRegistro DEFAULT GETDATE(),
	Telefono VARCHAR(10) CONSTRAINT CK_IAContacto_Telefono CHECK(LEN(Telefono) = 10) UNIQUE,
	Nombre VARCHAR(50) NOT NULL,
	IdUsuario INT NOT NULL,
	PRIMARY KEY(IdConctacto),
	FOREIGN KEY (IdUsuario) REFERENCES IAUsuario(IdUsuario) ON DELETE CASCADE
);
/*INDICE PARA CONSULTAS POR MEDIO DE NICKNAME Y CORREO*/
CREATE INDEX IX_IAUsuario_Nickname_Correo ON IAUsuario(Nickname, Correo) INCLUDE(IdUsuario, Contrasena, Estatus) WITH(FILLFACTOR=80, DATA_COMPRESSION=PAGE)
CREATE INDEX IX_IAContacto_Telefono_Nombre ON IAContacto(Telefono, Nombre) INCLUDE(IdUsuario, FechaRegistro, IdConctacto) WITH(FILLFACTOR=80, DATA_COMPRESSION=PAGE)

/*COMPRESION A NIVEL TABLA*/
ALTER TABLE IAUsuario REBUILD PARTITION = ALL
WITH
(
	DATA_COMPRESSION = PAGE
)
ALTER TABLE IAContacto REBUILD PARTITION = ALL
WITH
(
	DATA_COMPRESSION = PAGE
)

